import type { Post, Author, Category } from '@/types'

const img = { _type: 'image' as const, asset: { _ref: '', _type: 'reference' as const } }

export const PLACEHOLDER_CATEGORIES: Category[] = [
  { _id: 'c1', title: 'Writing', slug: { current: 'writing' }, color: 'amber' },
  { _id: 'c2', title: 'Productivity', slug: { current: 'productivity' }, color: 'emerald' },
  { _id: 'c3', title: 'Building', slug: { current: 'building' }, color: 'sky' },
]

export const PLACEHOLDER_AUTHOR: Author = {
  _id: 'a1',
  name: 'Your Name',
  bio: 'Writer and creator exploring the intersections of technology, creativity, and intentional living. I write about building things, thinking clearly, and the daily practice of creative work.',
  image: img,
  twitter: '@yourhandle',
}

export const PLACEHOLDER_POSTS: Post[] = [
  {
    _id: '1',
    _createdAt: '2024-03-15T00:00:00Z',
    title: 'The Quiet Art of Writing Every Day',
    slug: { current: 'writing-every-day' },
    excerpt: 'How building a daily writing habit changed the way I think, create, and connect with ideas — and why you don\'t need an audience to start.',
    publishedAt: '2024-03-15',
    estimatedReadingTime: 5,
    isPremium: false,
    mainImage: img,
    categories: [PLACEHOLDER_CATEGORIES[0]],
    author: PLACEHOLDER_AUTHOR,
    body: [],
  },
  {
    _id: '2',
    _createdAt: '2024-03-08T00:00:00Z',
    title: 'How I Organize My Research Notes',
    slug: { current: 'organizing-research-notes' },
    excerpt: 'A system for capturing, connecting, and retrieving ideas — without turning your notes into a second job.',
    publishedAt: '2024-03-08',
    estimatedReadingTime: 7,
    isPremium: false,
    mainImage: img,
    categories: [PLACEHOLDER_CATEGORIES[1]],
    author: PLACEHOLDER_AUTHOR,
    body: [],
  },
  {
    _id: '3',
    _createdAt: '2024-03-01T00:00:00Z',
    title: 'Building in Public: Lessons from Year One',
    slug: { current: 'building-in-public-year-one' },
    excerpt: 'What I learned from sharing my work openly — the unexpected benefits, the hard moments, and why I\'d do it again.',
    publishedAt: '2024-03-01',
    estimatedReadingTime: 8,
    isPremium: true,
    mainImage: img,
    categories: [PLACEHOLDER_CATEGORIES[2]],
    author: PLACEHOLDER_AUTHOR,
    body: [],
  },
  {
    _id: '4',
    _createdAt: '2024-02-22T00:00:00Z',
    title: 'Why I Write with a Pen First',
    slug: { current: 'write-with-pen-first' },
    excerpt: 'The case for slowing down before you speed up — and how analog tools change the quality of digital work.',
    publishedAt: '2024-02-22',
    estimatedReadingTime: 4,
    isPremium: false,
    mainImage: img,
    categories: [PLACEHOLDER_CATEGORIES[0]],
    author: PLACEHOLDER_AUTHOR,
    body: [],
  },
  {
    _id: '5',
    _createdAt: '2024-02-15T00:00:00Z',
    title: 'The Compound Effect of Consistent Output',
    slug: { current: 'compound-effect-consistent-output' },
    excerpt: 'Small actions, taken consistently, produce results that feel impossible from the starting line. Here\'s how to trust the math.',
    publishedAt: '2024-02-15',
    estimatedReadingTime: 6,
    isPremium: false,
    mainImage: img,
    categories: [PLACEHOLDER_CATEGORIES[1]],
    author: PLACEHOLDER_AUTHOR,
    body: [],
  },
  {
    _id: '6',
    _createdAt: '2024-02-08T00:00:00Z',
    title: 'Finding Your Voice: A Framework',
    slug: { current: 'finding-your-voice' },
    excerpt: 'Voice isn\'t something you find — it\'s something you build, sentence by sentence, over thousands of hours of practice.',
    publishedAt: '2024-02-08',
    estimatedReadingTime: 9,
    isPremium: true,
    mainImage: img,
    categories: [PLACEHOLDER_CATEGORIES[0]],
    author: PLACEHOLDER_AUTHOR,
    body: [],
  },
]
